DECLARE @YEAR VARCHAR(4) = '2021';

SELECT
    TF.AL_ITEM_NAME AS Folder_Name,

    SUM(CASE
            WHEN UPPER(T.TS_NAME) LIKE 'TA_%'
            THEN 1 ELSE 0
        END) AS Automated_Count,

    SUM(CASE
            WHEN UPPER(T.TS_NAME) NOT LIKE 'TA_%'
            THEN 1 ELSE 0
        END) AS Manual_Count,

    COUNT(*) AS Total_Count

FROM TEST T
INNER JOIN ALL_LISTS TF
    ON T.TS_SUBJECT = TF.AL_ITEM_ID

WHERE TF.AL_ITEM_NAME LIKE '%' + @YEAR + '%'

GROUP BY TF.AL_ITEM_NAME
ORDER BY TF.AL_ITEM_NAME;
