DECLARE @YEAR VARCHAR(4) = '2021';

SELECT 
    CY.CY_CYCLE AS Folder_Name,

    SUM(CASE 
            WHEN UPPER(TS.TS_NAME) LIKE 'TA_%'
            THEN 1 ELSE 0
        END) AS Automated_Count,

    SUM(CASE 
            WHEN UPPER(TS.TS_NAME) NOT LIKE 'TA_%'
            THEN 1 ELSE 0
        END) AS Manual_Count,

    COUNT(*) AS Total_Count

FROM TEST TS
INNER JOIN TESTCYCL TC
    ON TS.TS_TEST_ID = TC.TC_TEST_ID

INNER JOIN CYCLE CY
    ON TC.TC_CYCLE_ID = CY.CY_CYCLE_ID

WHERE CY.CY_CYCLE LIKE '%' + @YEAR + '%'

GROUP BY CY.CY_CYCLE
ORDER BY CY.CY_CYCLE;
